const fonts = {
  black: 'Poppins-Black',
  bold: 'Poppins-Bold',
  extraBold: 'Poppins-ExtraBold',
  blackItalic: 'Poppins-BlackItalic',
  boldItalic: 'Poppins-BoldItalic',
  extraBoldItalic: 'Poppins-ExtraBoldItalic',
  extraLightItalic: 'Poppins-ExtraLightItalic',
  italic: 'Poppins-Italic',
  light: 'Poppins-Light',
  lightItalic: 'Poppins-LightItalic',
  medium: 'Poppins-Medium',
  mediumItalic: 'Poppins-MediumItalic',
  regular: 'Poppins-Regular',
  semiBold: 'Poppins-SemiBold',
  semiBoldItalic: 'Poppins-SemiBoldItalic',
  montserrat: 'Montserrat',
  montserratMedium: 'Montserrat-Medium',
  montserratLight: 'Montserrat-Light',
  montserratRegular: 'Montserrat-Regular',
  montserratBold: 'Montserrat-Bold',
};
export default fonts;
